[package]
name = "zellij-console"
version = "0.1.0"
authors = ["Zykino <>"]
edition = "2021"

[dependencies]
ansi_term = "0.12.1"
chrono = "0.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
zellij-tile = "0.37.0"
